### Variáveis Globais
@baseUrl = http://localhost:3501
@name = teste2
@email = teste2@fatec.com
@password = 022

### 1. Criar um novo usuário (Sign Up)
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
    "name": " {{name}}",
    "login" : "{{email}}",
    "password": "{{password}}"
}

### 2. Realizar Login (Gera o Token JWT)
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "login": "{{email}}",
    "password": "{{password}}"
}
### Armazenar o token da resposta acima
@authToken = {{login.response.body.token}}

### 3. Listar Usuários (Rota Protegida)
GET {{baseUrl}}/users
Authorization: Bearer {{authToken}}

###
GET {{baseUrl}}/users/14