@host = http://localhost
@port = 3501
@endpoint = users

@url = {{host}}:{{port}}/{{endpoint}} 

###
GET {{url}}

###
# getById
GET {{url}}/1

###
# getByEmail
GET {{url}}/email/provara022@fatec.co

###
# inclui novos registros
POST  {{url}}
Content-Type: application/json; charset=utf-8

{
      "name": "prova 022",
      "password": "022",
      "login" : "provara022@fatec.com"
    }

###

PUT  {{url}}/2
Content-Type: application/json; charset=utf-8

{
    "name": "teste.022",
    "password": "022",
    "password": "123-456"    
}

###
DELETE  {{url}}/3
Content-Type: application/json; charset=utf-8

